spring:
  sql:
    init:
      continue-on-error: 'true'
      mode: always
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5455/tasks
    password: secret
    initialize: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
    hibernate:
      show-sql: 'true'
  flyway:
    locations: "classpath:db/migration"
